/**
 * models/imageModel.js
 * ─────────────────────────────────────────────────────────
 * Firestore "images" collection schema and constants
 *
 * Document ID = auto-generated by Firestore
 *
 * ┌─────────────────── Image Lifecycle ───────────────────┐
 * │  Seller uploads → PENDING → Admin reviews             │
 * │  Admin approves → APPROVED (live, buyable)            │
 * │  Admin rejects  → REJECTED (seller sees reason)       │
 * │  Seller hides   → INACTIVE (hidden from browse)       │
 * │  Seller/Admin   → DELETED  (soft-deleted)             │
 * └───────────────────────────────────────────────────────┘
 */
const { FieldValue } = require('../config/firebase');

// ── Status constants ───────────────────────────────────────────────────────
const IMAGE_STATUS = Object.freeze({
  PENDING:  'pending',    // Just uploaded, awaiting admin review
  APPROVED: 'approved',   // Live and purchasable by buyers
  REJECTED: 'rejected',   // Admin rejected — seller can fix and re-upload
  INACTIVE: 'inactive',   // Hidden by seller
  DELETED:  'deleted',    // Soft-deleted (not shown anywhere)
});

// ── Valid categories ───────────────────────────────────────────────────────
const IMAGE_CATEGORIES = [
  'nature',
  'architecture',
  'people',
  'animals',
  'technology',
  'food',
  'travel',
  'abstract',
  'fashion',
  'sports',
  'other',
];

/**
 * Build a new image document for Firestore
 *
 * @param {object} params
 * @param {string} params.sellerId
 * @param {string} params.sellerName
 * @param {string} params.imageName       — display title
 * @param {string} params.description
 * @param {number} params.price
 * @param {string} params.category
 * @param {string[]} params.tags
 * @param {string} params.watermarkUrl    — public Cloudinary URL (watermarked)
 * @param {string} params.watermarkPublicId
 * @param {string} params.originalPublicId — private Cloudinary resource
 * @param {object} params.metadata        — width, height, format, bytes
 */
const createImageDocument = ({
  sellerId,
  sellerName,
  imageName,
  description = '',
  price,
  category,
  tags = [],
  watermarkUrl,
  watermarkPublicId,
  originalPublicId,
  metadata = {},
}) => ({
  sellerId,
  sellerName,
  imageName: imageName.trim(),
  description: description.trim(),
  price,
  category,
  tags: tags.map((t) => t.toLowerCase().trim()).filter(Boolean),

  // ── Cloudinary references ──────────────────────────────────────────────
  watermarkUrl,                   // 🌐 Public — safe for buyers to see
  watermarkPublicId,              // For deleting preview from Cloudinary
  originalPublicId,               // 🔒 Private — only via signed URL after purchase

  // ── Image technical metadata ───────────────────────────────────────────
  metadata: {
    width:  metadata.width  || null,
    height: metadata.height || null,
    format: metadata.format || null,
    bytes:  metadata.bytes  || null,
  },

  // ── Status & moderation ────────────────────────────────────────────────
  status: IMAGE_STATUS.PENDING,   // All uploads start as pending
  adminNote: null,                 // Admin rejection reason (visible to seller)
  isFeatured: false,               // Admin can feature selected images

  // ── Engagement stats ───────────────────────────────────────────────────
  views: 0,
  purchases: 0,
  likes: 0,

  // ── Timestamps ────────────────────────────────────────────────────────
  uploadDate: FieldValue.serverTimestamp(),   // Named "uploadDate" to match API spec
  updatedAt:  FieldValue.serverTimestamp(),
  approvedAt: null,
});

/**
 * Build the public-safe image object for API responses
 * Strips private fields (originalPublicId, watermarkPublicId)
 */
const sanitizeImage = (imageDoc) => {
  const { originalPublicId, watermarkPublicId, ...safe } = imageDoc;
  return safe;
};

module.exports = { IMAGE_STATUS, IMAGE_CATEGORIES, createImageDocument, sanitizeImage };